# Generated by Django 3.2.12 on 2022-04-07 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20220405_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sheet Head',
                'verbose_name_plural': 'Sheet Heads',
            },
        ),
        migrations.CreateModel(
            name='WeeklyConsolidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('net_sale_amount', models.DecimalField(decimal_places=2, max_digits=500)),
                ('net_sale_percentage', models.DecimalField(decimal_places=2, max_digits=500)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidate', to='analytics.week')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
        migrations.RemoveField(
            model_name='expensename',
            name='head',
        ),
        migrations.RemoveField(
            model_name='incomename',
            name='head',
        ),
        migrations.DeleteModel(
            name='ExpenseHead',
        ),
        migrations.DeleteModel(
            name='ExpenseName',
        ),
        migrations.DeleteModel(
            name='IncomeHead',
        ),
        migrations.DeleteModel(
            name='IncomeName',
        ),
    ]
