# Generated by Django 3.2.12 on 2022-04-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_auto_20220407_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyconsolidate',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_weekly_consolidate', to='analytics.store'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyconsolidate',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_weekly_consolidate', to='analytics.week'),
        ),
    ]
