# Generated by Django 3.2.12 on 2022-04-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20220407_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyconsolidate',
            options={'verbose_name': 'Weekly Consolidate', 'verbose_name_plural': 'Weekly Consolidate'},
        ),
    ]
