# Generated by Django 3.2.12 on 2022-05-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_weeklyconsolidatedetail_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='analytics.store')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.week')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='BudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_detail', to='analytics.budget')),
                ('sheet_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.sheethead')),
            ],
            options={
                'verbose_name': 'BudgetDetail',
                'verbose_name_plural': 'BudgetDetails',
            },
        ),
    ]
