# Generated by Django 3.2.12 on 2022-05-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_budget_budgetdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetdetail',
            options={'verbose_name': 'Budget Detail', 'verbose_name_plural': 'Budget Details'},
        ),
    ]
